// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8cSSj_Q2hTUbfMwK3N6mOBgW0qTGQTKQ',
    appId: '1:896054401280:web:b59b2d361c5b53550ffbe5',
    messagingSenderId: '896054401280',
    projectId: 'blog-app-8b5be',
    authDomain: 'blog-app-8b5be.firebaseapp.com',
    storageBucket: 'blog-app-8b5be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJJoT030BDscOENrXHMJxnZHHqSJWPZ8c',
    appId: '1:896054401280:android:2a95071ecbbea5760ffbe5',
    messagingSenderId: '896054401280',
    projectId: 'blog-app-8b5be',
    storageBucket: 'blog-app-8b5be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWLxaXflEZAVdainUUyE9MTMH5WpqajZE',
    appId: '1:896054401280:ios:b8f98ece723f11cc0ffbe5',
    messagingSenderId: '896054401280',
    projectId: 'blog-app-8b5be',
    storageBucket: 'blog-app-8b5be.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWLxaXflEZAVdainUUyE9MTMH5WpqajZE',
    appId: '1:896054401280:ios:45ca33bd1fbe38330ffbe5',
    messagingSenderId: '896054401280',
    projectId: 'blog-app-8b5be',
    storageBucket: 'blog-app-8b5be.appspot.com',
    iosBundleId: 'com.example.blogApp.RunnerTests',
  );
}
